---
- name: Create a file on my EC2 
  hosts: all
  remote_user: ec2-user
  become: yes   
  tasks:
    - name: Create a file
      ansible.builtin.file:
        path: /home/ec2-user/test.txt  
        state: touch  
        
