---
# roles/jenkins/tasks/main.yml

- name: Install Java (Jenkins dependency)
  yum:
    name: java-11-openjdk
    state: present
  become: yes

- name: Import Jenkins GPG key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat/jenkins.io.key
  become: yes

- name: Install Jenkins repository
  get_url:
    url: https://pkg.jenkins.io/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
      
- name: Import Jenkins GPG key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat/jenkins.io-2023.key


- name: Install Java 17
  yum:
    name: java-17-openjdk
    state: present

- name: Install Jenkins
  yum:
    name: jenkins
    state: present



